import { PrismaClient } from '@prisma/client';
import * as bcrypt from 'bcrypt';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database...');

  // Seed units
  const units = [
    { name: 'atado', abbreviation: null },
    { name: 'botella', abbreviation: null },
    { name: 'cabeza', abbreviation: null },
    { name: 'cucharada', abbreviation: "cda" },
    { name: 'cucharadita', abbreviation: "cdita" },
    { name: 'diente', abbreviation: null },
    { name: 'filete', abbreviation: null },
    { name: 'gramo', abbreviation: "g" },
    { name: 'hoja', abbreviation: null },
    { name: 'kilogramo', abbreviation: "kg" },
    { name: 'lata', abbreviation: null },
    { name: 'litro', abbreviation: "L" },
    { name: 'manojo', abbreviation: null },
    { name: 'mililitro', abbreviation: "ml" },
    { name: 'pizca', abbreviation: null },
    { name: 'puñado', abbreviation: null },
    { name: 'rama', abbreviation: null },
    { name: 'rebanada', abbreviation: null },
    { name: 'rodaja', abbreviation: null },
    { name: 'sobre', abbreviation: null },
    { name: 'tallo', abbreviation: null },
    { name: 'taza', abbreviation: "tza" },
    { name: 'trozo', abbreviation: null },
    { name: 'unidad', abbreviation: null },
    { name: 'vaso', abbreviation: null },
  ];

  for (const unit of units) {
    await prisma.unit.upsert({
      where: { name: unit.name },
      update: {},
      create: unit,
    });
  }
  console.log(`Seeded ${units.length} units`);

  // Seed common foods
  const foods = [
    'abadejo',
    'aceite',
    'aceite de girasol',
    'aceite de girasol o maíz',
    'aceite de maíz',
    'aceite de oliva',
    'aceite de oliva extra virgen',
    'aceite de oliva virgen extra',
    'aceite neutro',
    'aceite o papel manteca',
    'aceite para freír',
    'aceite para freír o para rociar',
    'aceite para hornear o para freír',
    'aceite vegetal',
    'aceitunas',
    'aceitunas negras',
    'aceitunas sin carozo',
    'aceitunas verdes',
    'acelga',
    'aceto balsámico',
    'agar agar',
    'agua',
    'agua caliente',
    'agua filtrada',
    'agua o caldo de verduras',
    'agua o leche vegetal',
    'agua tibia',
    'aguardiente o pisco chileno',
    'ajo',
    'ajo en polvo',
    'ají',
    'ají amarillo sin venas ni semillas',
    'ají molido',
    'ají morrón',
    'ají picante',
    'ajíes de colores',
    'albahaca',
    'alcaparras',
    'alcauciles',
    'alitas de pollo',
    'almejas',
    'almendras',
    'almendras crudas',
    'almendras fileteadas',
    'almidón',
    'almidón de maíz',
    'almíbar',
    'alubias blancas',
    'amaranto',
    'amarettis',
    'ananá',
    'anchoas',
    'ande de espinacas',
    'anis estrellado',
    'anís estrellado',
    'apio',
    'arañitas',
    'arroz',
    'arroz blanco',
    'arroz blanco cocido para acompañar',
    'arroz de grano redondo',
    'arroz doble carolina',
    'arroz jazmín',
    'arvejas',
    'arándanos',
    'arándanos frescos',
    'asado americano',
    'atado grande de perejil',
    'atún',
    'atún al natural o en aceite',
    'avellanas',
    'azafrán',
    'azúcar',
    'azúcar blanca',
    'azúcar glas',
    'azúcar impalpable',
    'azúcar morena',
    'azúcar moreno o endulzante al gusto',
    'azúcar negra',
    'azúcar rubia',
    'azúcar rubio',
    'bacalao desalado en migas',
    'bacalao en salazón',
    'baguette en rodajas finas',
    'banana',
    'batata',
    'batatas',
    'berenjena',
    'berenjenas',
    'bicarbonato',
    'bicarbonato de sodio',
    'bife de chorizo',
    'blinis o tostadas finas de pan neutro',
    'bolsitas de té negro',
    'bondiola',
    'boniato',
    'brillo para fruta',
    'brotes de soja',
    'bulbos de hinojo',
    'cabrito',
    'cabutia',
    'cacao amargo',
    'café instantáneo',
    'café molido para cafetera italiana',
    'calabaza',
    'calamar',
    'calamares',
    'caldo',
    'caldo de pescado o agua',
    'caldo de pollo',
    'caldo de pollo o verduras',
    'caldo de verdura',
    'canela',
    'canela en polvo',
    'carne de centolla cocida y desmenuzada',
    'carne de cerdo picada',
    'carne para mechar',
    'carne picada',
    'carne picada mixta',
    'carré de cerdo',
    'cayote',
    'cebada perlada',
    'cebolla',
    'cebolla colorada',
    'cebolla crispy',
    'cebolla de verdeo',
    'cebolla en cubitos',
    'cebolla morada',
    'cebolla roja',
    'cebollas',
    'cebolleta',
    'cebollino',
    'cebollino o ciboulette finamente',
    'cerdo',
    'cereal sin azúcar',
    'cereza',
    'cereza al marrasquino',
    'cerezas',
    'cerezas al marrasquino',
    'cerveza',
    'cerveza negra',
    'champiñones',
    'chaucha',
    'chauchas',
    'chauchas planas',
    'chile',
    'chile jalapeño',
    'chile rojo',
    'chinchulines de vaca',
    'choclo',
    'chocolate amargo',
    'chocolate blanco',
    'chocolate con leche',
    'chocolate semi amargo',
    'chocolate semiamargo',
    'chorizo',
    'chorizo asturiano',
    'chorizo colorado en rodajas',
    'chorizos de cerdo',
    'chorrito de aceite de oliva',
    'chorrito de caldo para aligerar la salsa',
    'chorrito de vinagre',
    'chuletas de cerdo',
    'churrasquito de cerdo',
    'cilantro',
    'ciruelas',
    'clara de huevo',
    'claras',
    'claras de huevo',
    'clavo de olor',
    'clavos de olor',
    'cochinillo lechal',
    'coco',
    'coco rallado',
    'cognac',
    'coliflor',
    'colita de cuadril',
    'colorante',
    'colorante alimentario rojo',
    'colorante vegetal amarillo',
    'colorante vegetal rojo',
    'colorante verde',
    'comino',
    'compota de frutillas',
    'confitura de frutillas',
    'copos de maíz',
    'coriandro',
    'costillas de cerdo',
    'coñac',
    'crema',
    'crema agria o crème fraîche',
    'crema de leche',
    'crema de leche para cocinar',
    'crema de queso',
    'crema para batir',
    'cuero de cerdo',
    'curry',
    'cuscús',
    'cynar',
    'cúrcuma',
    'damascos frescos',
    'dulce casero de frambuesa',
    'dulce casero de maracuyá',
    'dulce de leche',
    'dulce de leche repostero',
    'dulce de leche repostero para rellenar',
    'durazno',
    'eneldo fresco y perejil',
    'entraña',
    'entrañas',
    'escarola',
    'escarola rizada',
    'esencia de frambuesa',
    'esencia de limón',
    'esencia de maracuyá',
    'esencia de vainilla',
    'espaguetis o la pasta que se prefiera',
    'especias para pastelería',
    'espinaca',
    'espinaca fresca',
    'espárragos',
    'estragón',
    'estrella de anís',
    'extracto de carne',
    'extracto de tomate',
    'extracto de vainilla',
    'falda de res sin grasa',
    'fideos',
    'filet de pescado',
    'filet de surubí',
    'filetes de ternera u otra carne magra',
    'frambuesa',
    'frambuesas',
    'frutas confitadas o pepitas de chocolate',
    'frutilla',
    'frutillas',
    'frutos rojos',
    'frutos secos',
    'fécula de maíz',
    'galletas de vainilla o chocolate',
    'gambas',
    'ganache de chocolate',
    'garbanzos',
    'garrofón',
    'gelatina',
    'gelatina sin sabor',
    'gianduia',
    'glucosa',
    'granos de mostaza',
    'granos de pimienta negra',
    'grasa',
    'grasa de cerdo',
    'guisantes en lata o congelados',
    'habichuelas blancas',
    'harina',
    'harina común',
    'harina común para espolvorear',
    'harina de almendra',
    'harina de almendras',
    'harina de arroz',
    'harina de avena',
    'harina de centeno integral',
    'harina de fuerza',
    'harina de garbanzo',
    'harina de maíz',
    'harina de millo',
    'harina de trigo',
    'harina de trigo común',
    'harina de trigo de fuerza',
    'harina de trigo sarraceno',
    'harina de trigo todo uso',
    'harina integral',
    'harina leudante',
    'hielo',
    'hierbas',
    'hierbas duras',
    'hierbas frescas',
    'higo',
    'higos',
    'hinojo',
    'hinojo en semillas',
    'huevo',
    'huevo duro',
    'huevos',
    'huevos duros',
    'hígado',
    'indilla o peperoncino',
    'jalapeños',
    'jalea de frambuesa',
    'jalea de naranja',
    'jamón',
    'jamón cocido',
    'jamón crudo',
    'jengibre',
    'jengibre fresco',
    'jengibre seco',
    'judías verdes',
    'judías verdes planas',
    'jugo de lima',
    'jugo de limón',
    'jugo de limón o vinagre',
    'jugo de maracuyá',
    'jugo de medio pomelo',
    'jugo de naranja',
    'ketchup',
    'kiwi',
    'langostino',
    'laurel',
    'leche',
    'leche condensada',
    'leche de cabra',
    'leche de coco',
    'leche en polvo',
    'leche entera',
    'leche evaporada o leche común',
    'leche tibia',
    'lechuga',
    'lechuga mantecosa',
    'lentejas',
    'levadura',
    'levadura de cerveza',
    'levadura fresca',
    'levadura fresca de panadero',
    'levadura nutricional',
    'levadura seca',
    'levadura seca de panadero',
    'licor amaretto',
    'lima',
    'limones',
    'limón',
    'linguini',
    'lomo de res',
    'lonchas de bacon o panceta',
    'lonchas de jamón tipo york',
    'lonchas de queso',
    'lt. de caldo de verduras o agua',
    'macarons',
    'manitas de cerdo',
    'manteca',
    'manteca a temperatura ambiente',
    'manteca clarificada',
    'manteca de cacao',
    'manteca fría',
    'manteca sin sal',
    'mantequilla',
    'mantequilla a temperatura ambiente',
    'mantequilla de maní',
    'mantequilla o aceite',
    'mantequilla sin sal',
    'manzana',
    'manzanas',
    'maní',
    'mascarpone',
    'mastuerzo',
    'matambre',
    'mayonesa',
    'mazorcas de maíz',
    'mejillón',
    'menta',
    'merengue',
    'merengue italiano',
    'mermelada',
    'mermelada de frambuesa',
    'mermelada de naranja',
    'miel',
    'miel de maple o de abeja',
    'miel de palma o miel común',
    'miel o sirope de arce',
    'miga de pan',
    'mollejas',
    'mollejas de corazón',
    'mollejas de ternera',
    'mora',
    'moras',
    'morcilla',
    'morcillas bombón',
    'morcillas de burgos o de cebolla',
    'morrones',
    'morrón',
    'morrón asado',
    'morrón rojo',
    'morrón rojo o verde',
    'mortadela',
    'morón amarillo',
    'morón rojo',
    'morón verde',
    'mostaza',
    'mostaza de dijón',
    'mozarela fior de leche',
    'mozzarella',
    'nalga',
    'nalga de ternera',
    'naranja',
    'nas hebras de azafrán',
    'nas hojas de albahaca',
    'nas ramitas de romero',
    'nata para cocinar',
    'nueces',
    'nuez',
    'nuez moscada',
    'nuez pecan',
    'olivas',
    'oporto',
    'orégano',
    'osobuco',
    'paleta de cordero',
    'palta',
    'pan',
    'pan de hamburguesa',
    'pan de molde',
    'pan de molde blanco',
    'pan de molde sin corteza',
    'pan del día anterior',
    'pan lactal',
    'pan para acompañar',
    'pan rallado',
    'pan tipo baguette o chapata',
    'panceta',
    'panceta ahumada',
    'panceta curada',
    'panceta en cubos',
    'panko',
    'papa',
    'papa pastusa',
    'papa sabanera',
    'papas',
    'papas a la francesa para acompañar',
    'papas criollas',
    'papas fritas',
    'papas harinosas',
    'papas hervidas en rodajas',
    'papel aluminio',
    'papel de hornear o aceite',
    'parmesano rallado',
    'pasas de uva',
    'pasta de ají amarillo',
    'pasta de maní',
    'pata muslo de pollo',
    'patamuslo de pollo',
    'patatas',
    'pechuga de pollo',
    'pechuga de pollo cocida y en rebanadas',
    'pechugas de pollo',
    'pelón',
    'pepino',
    'pepinos en conserva',
    'pequeño de eneldo',
    'peras',
    'perejil',
    'pez espada',
    'picaña',
    'pickles de cebolla',
    'piel de limón',
    'piel de naranja',
    'piezas de pollo',
    'pimentón',
    'pimentón dulce',
    'pimentón dulce de la vera',
    'pimentón picante',
    'pimienta',
    'pimienta blanca',
    'pimienta en granos y en polvo',
    'pimienta negra',
    'pimienta negra al gusto',
    'pimienta negra en grano',
    'pimienta negra recién',
    'pimienta negra recién molida al gusto',
    'pimiento',
    'pimiento asado o en conserva',
    'pimiento rojo',
    'pimiento verde',
    'pistachos',
    'plancha de hojaldre',
    'plátano maduro',
    'polenta instantánea',
    'pollo',
    'polvo de almendras',
    'polvo de hornear',
    'polvo de remolacha',
    'polvo para hornear',
    'porotos negros',
    'premezcla sin tacc',
    'provoleta',
    'puerro',
    'pulpa de frambuesa',
    'pulpa de maracuyá',
    'puré de papa',
    'puré de tomate',
    'queso',
    'queso azul',
    'queso blanco',
    'queso brie',
    'queso cheddar',
    'queso crema',
    'queso cremoso',
    'queso de cabra',
    'queso de cabra o feta',
    'queso fontina',
    'queso gruyere',
    'queso mascarpone',
    'queso mozzarella',
    'queso muzzarela',
    'queso para gratinar',
    'queso parmesano',
    'queso parmesano rallado',
    'queso rallado',
    'queso regianito',
    'queso roquefort',
    'quinoa',
    'ralladura de lima',
    'ralladura de limón',
    'ralladura de naranja',
    'remolacha',
    'repollo blanco',
    'repollo rojo',
    'ribs de cerdo',
    'ricota',
    'riñones de vaca',
    'romero',
    'romero fresco',
    'romero o tomillo',
    'rúcula',
    'sal',
    'sal al gusto',
    'sal fina',
    'sal fina al gusto',
    'sal gruesa',
    'sal gruesa y sal fina',
    'sal parrillera',
    'sal parrillera o entrefina',
    'sal y pimienta',
    'sal y pimienta al gusto',
    'sal y pimienta negra recién',
    'salmón ahumado',
    'salsa bechamel',
    'salsa de chocolate',
    'salsa de ostras',
    'salsa de pescado',
    'salsa de soja',
    'salsa de tomate',
    'salsa hoisin',
    'salsa inglesa',
    'salvia',
    'semillas',
    'semillas al gusto',
    'semillas de girasol',
    'semillas de hinojo',
    'semillas de mostaza',
    'semillas de sésamo',
    'semillas de sésamo tostado',
    'semillas mix',
    'sidra',
    'soja texturizada',
    'sémola de trigo duro',
    'sémola de trigo duro remolida',
    'sémola extra para espolvorear',
    'sémola rimacinata',
    'sésamo',
    'tabasco',
    'tapa de asado',
    'tiras de tocino',
    'tocino ahumado',
    'tomate',
    'tomate cherry',
    'tomate en rodajas',
    'tomate perita',
    'tomate redondo',
    'tomate triturado',
    'tomates cherry',
    'tomates confitados',
    'tomates maduros',
    'tomates perita',
    'tomates secos',
    'tomillo',
    'trocito de jengibre',
    'tubos de calamar',
    'uvas',
    'vacío',
    'vaina de vainilla',
    'vainas de cardamomo',
    'verdeo',
    'verdolaga',
    'vinagre',
    'vinagre de alcohol',
    'vinagre de manzana',
    'vinagre de torrontés',
    'vinagre de vino',
    'vinagre de vino tinto',
    'vino blanco',
    'vino blanco o caldo',
    'vino marzala',
    'vino tinto',
    'yema',
    'yemas de huevo',
    'yogurt',
    'yogurt natural',
    'zanahoria',
    'zanahoria cocida en rodajas',
    'zanahorias',
    'zapallo',
    'zapallo inglés',
    'zucchini',
  ];

  for (const name of foods) {
    await prisma.food.upsert({
      where: { name },
      update: {},
      create: { name },
    });
  }
  console.log(`Seeded ${foods.length} foods`);

  // Seed dev admin account
  const adminEmail = 'admin@example.com';
  const adminPassword = 'admin123';
  const passwordHash = await bcrypt.hash(adminPassword, 10);

  await prisma.admin.upsert({
    where: { email: adminEmail },
    update: {},
    create: {
      name: 'Admin',
      email: adminEmail,
      passwordHash,
    },
  });
  console.log(`Seeded dev admin: ${adminEmail} / ${adminPassword}`);

  console.log('Seeding complete.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
